# Docker compose file for Ubuntu 24.04 ROS 2 Jazzy

services:
  ros_jazzy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROSBAG_SRC_FOLDER: ${BAG2VID_SRC}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${BAG2VID_SRC}:/home/ubuntu/rosbags
    command: /bin/bash
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    tty: true
    privileged: true
