# Docker compose file for ubuntu 18.04 ros melodic
version: '3.9'

services:
  ros_melodic:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROSBAG_SRC_FOLDER: ${BAG2VID_SRC}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${BAG2VID_SRC}:/home/user/rosbags
    command: /bin/bash
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    tty: true
    privileged: true
    
  ros2_jazzy:
    build:
      context: .
      dockerfile: Dockerfile.ros2
      args:
        ROSBAG_SRC_FOLDER: /Users/stathi/Downloads
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/stathi/Downloads:/home/user/rosbags
    command: /bin/bash
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: host
    tty: true
    privileged: true