# Docker compose file for Ubuntu 24.04 ROS 2 Jazzy

services:
  ros_jazzy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}:${HOME}
    command: /bin/bash
    environment:
      - DISPLAY=${DISPLAY}
      - HOME=${HOME}
    network_mode: host
    tty: true
    privileged: true
