<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>bag2vid</name>
  <version>2.0.0</version>
  <description>GUI tool for extracting videos from rosbags</description>
  <maintainer email="stathi.weir@gmail.com">Stathi Weir</maintainer>
  <license>GPLv3 + Commons Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rosbag2_cpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
